id = "kasl"
name = "KASL"
version = "0.0.1"
schema_version = 1
authors = ["Shuntaro Kasatani <shuntar30@gmail.com>"]
description = "A KASL language support for Zed."
repository = "https://github.com/hatya-mouse/kasl_zed"

[grammars.kasl]
repository = "https://github.com/hatya-mouse/tree-sitter-kasl"
rev = "b20d3b4da2a18eebda1aebadee43478d05ed2c8d"
